# Introduction {#intro}

This misuse of and addiction to opioids has been recognized as serious national
crisis that affects public health as well as social and economic welfare. Policies are needed to
counteract the widespread use of opioids, prescriptions as well as illicit. How to evaluate the
effect of policies using artificial societies is not yet well understood. Using data from open
sources, this Project seeks to calibrate and initialize an artificial society utilizing an existing high
resolution agent based model of the National Capital Region that allows stakeholders to evaluate
the incidence and progression of the opioid crisis and explicitly address the relevant social
determinants of health (“SDOH”) by modeling patients as well as their relevant social networks,
family, church, clubs, workplaces, etc. This allows for a bottom up approach in which reactions
emerge. The outcome will be an interactive simulation model with tools that allow for an initial
evaluation using SDOH that will be validated using results from studies and other models. The
results will be presented to the professional and academic health centers and caregivers.
